version: '3'

services:

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=your_lastname
      - POSTGRES_USER=your_lastname
      - POSTGRES_PASSWORD=your_lastname
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  python:
    build: .
    environment:
      - POSTGRES_DB=your_lastname
      - POSTGRES_USER=your_lastname
      - POSTGRES_PASSWORD=your_lastname
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    entrypoint: python3 app.py

volumes:
  postgres-data:
